import { BLACK, EMPTY, Board, WHITE } from '../../interfaces/game';

export const basicGame1: Board = [
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: WHITE },
        { type: BLACK },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: BLACK },
        { type: BLACK },
        { type: WHITE },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: WHITE },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
];

export const basicGame2: Board = [
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: WHITE },
        { type: WHITE },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: BLACK },
        { type: WHITE },
        { type: BLACK },
        { type: WHITE },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: BLACK },
        { type: WHITE },
        { type: BLACK },
        { type: BLACK },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: BLACK },
        { type: BLACK },
        { type: BLACK },
        { type: BLACK },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
    [
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
        { type: EMPTY },
    ],
];

export const endGame: Board = [
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: BLACK },
        { type: WHITE },
        { type: BLACK },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: BLACK },
        { type: WHITE },
        { type: BLACK },
        { type: BLACK },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: BLACK },
        { type: BLACK },
        { type: BLACK },
        { type: BLACK },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
];

export const basicGame3: Board = [
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: BLACK },
        { type: WHITE },
        { type: WHITE },
        { type: EMPTY },
    ],
];

export const basicGame4: Board = [
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
    ],
    [
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: WHITE },
        { type: BLACK },
        { type: BLACK },
        { type: BLACK },
        { type: BLACK },
    ],
];
